<?php
########################################################################
# Extension Manager/Repository config file for ext: "cicrss"
#
# Auto generated by Extbase Kickstarter 2010-11-29
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'CIC RSS',
	'description' => 'An extension for consuming and displaying RSS feed data.',
	'category' => 'plugin',
	'author' => 'Michael McManus',
	'author_email' => 'michael@castironcoding.com',
	'author_company' => 'Cast Iron Coding, Inc',
	'shy' => '',
	'dependencies' => 'extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>